create extension if not exists pgcrypto;

create table if not exists public.skins (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  created_at timestamptz default now() not null
);

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  skin_id bigint not null references public.skins(id) on delete cascade,
  submitted_by uuid not null,
  submitted_discord_name text,
  storage_path text not null,
  public_url text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  notes text,
  created_at timestamptz default now() not null,
  reviewed_at timestamptz,
  reviewed_by uuid
);

create table if not exists public.admin_users (
  user_id uuid primary key,
  added_at timestamptz default now() not null
);

create or replace view public.approved_previews as
select
  s.id,
  s.skin_id,
  k.slug as skin_slug,
  k.name as skin_name,
  s.storage_path,
  s.public_url,
  s.created_at,
  s.submitted_discord_name
from public.submissions s
join public.skins k on k.id = s.skin_id
where s.status = 'approved';

grant usage on schema public to anon, authenticated;
grant select on public.skins to anon, authenticated;
grant select on public.approved_previews to anon, authenticated;
grant select, insert, update on public.submissions to authenticated;
grant select on public.admin_users to authenticated;

alter table public.skins enable row level security;
alter table public.submissions enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "skins are viewable by everyone" on public.skins;
create policy "skins are viewable by everyone"
on public.skins
for select
using (true);

drop policy if exists "users can insert own submissions" on public.submissions;
create policy "users can insert own submissions"
on public.submissions
for insert
to authenticated
with check (submitted_by = auth.uid());

drop policy if exists "users can view own submissions" on public.submissions;
create policy "users can view own submissions"
on public.submissions
for select
to authenticated
using (submitted_by = auth.uid());

drop policy if exists "admins can read all submissions" on public.submissions;
create policy "admins can read all submissions"
on public.submissions
for select
to authenticated
using (
  exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
  )
);

drop policy if exists "admins can update all submissions" on public.submissions;
create policy "admins can update all submissions"
on public.submissions
for update
to authenticated
using (
  exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.admin_users a
    where a.user_id = auth.uid()
  )
);

drop policy if exists "users can view own admin record" on public.admin_users;
create policy "users can view own admin record"
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

insert into storage.buckets (id, name, public)
values ('previews', 'previews', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "users can upload own pending previews" on storage.objects;
create policy "users can upload own pending previews"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'previews'
  and (storage.foldername(name))[1] = 'pending'
  and (storage.foldername(name))[2] = auth.uid()::text
);

drop policy if exists "users can delete own pending previews" on storage.objects;
create policy "users can delete own pending previews"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'previews'
  and (storage.foldername(name))[1] = 'pending'
  and (storage.foldername(name))[2] = auth.uid()::text
);
