-- Seed the public.skins table from the local static metadata.
insert into public.skins (slug, name)
values
  ('acid-secure-container-skin-pack', 'ACID SECURE CONTAINER SKIN PACK'),
  ('advanedge', 'ADVANEDGE'),
  ('ak74-wipe-reward', 'AK74 WIPE REWARD'),
  ('black-flag-secure-container-skin-pack', 'BLACK FLAG SECURE CONTAINER SKIN PACK'),
  ('black-ops', 'BLACK OPS'),
  ('boa', 'BOA'),
  ('boris-baton-secure-container-skin-pack', 'BORIS BATON SECURE CONTAINER SKIN PACK'),
  ('christmas', 'CHRISTMAS'),
  ('christmas-twitch-drop', 'Christmas_Twitch_Drop'),
  ('chromatic-heat', 'CHROMATIC HEAT'),
  ('club80', 'Club80'),
  ('comb', 'COMB'),
  ('cryptic-secure-container-skin-pack', 'CRYPTIC SECURE CONTAINER SKIN PACK'),
  ('easter', 'EASTER'),
  ('founding-fathers', 'FOUNDING FATHERS'),
  ('gk-secure-container-skin-pack', 'GK SECURE CONTAINER SKIN PACK'),
  ('grim-gun', 'GRIM GUN'),
  ('grim-reskin-2', 'GRIM RESKIN 2'),
  ('halloween', 'HALLOWEEN'),
  ('honey-badger-wipe-reward', 'HONEY BADGER WIPE REWARD'),
  ('independence', 'INDEPENDENCE'),
  ('kryptek', 'KRYPTEK'),
  ('luty-wipe-reward', 'LUTY WIPE REWARD'),
  ('m9-wipe-reward', 'M9 WIPE REWARD'),
  ('meta-review', 'META REVIEW'),
  ('neon-secure-container-skin-pack', 'NEON SECURE CONTAINER SKIN PACK'),
  ('nuclear-night', 'NUCLEAR NIGHT'),
  ('one-shot', 'ONE SHOT'),
  ('owo-too', 'OwO TOO'),
  ('payday', 'PAYDAY'),
  ('psvr-2-launch', 'PSVR 2 LAUNCH'),
  ('pve-team-tactics', 'PVE TEAM TACTICS'),
  ('rfcp', 'RFCP'),
  ('samurai-weapon-pack', 'SAMURAI WEAPON PACK'),
  ('skin-too-soft', 'SKIN TOO SOFT'),
  ('sks-tapco-christmas-special', 'SKS TAPCO CHRISTMAS SPECIAL'),
  ('splinter-cell', 'SPLINTER CELL'),
  ('steam-goty', 'STEAM GOTY'),
  ('stickers-secure-container-skin-pack', 'STICKERS SECURE CONTAINER SKIN PACK'),
  ('urban', 'URBAN'),
  ('uwu', 'UwU'),
  ('valentine-day-special', 'VALENTINE DAY SPECIAL'),
  ('x11-camo-black-comb', 'X11 CAMO – BLACK COMB'),
  ('x11-camo-blue-tiger', 'X11 CAMO – BLUE TIGER'),
  ('x11-camo-grassland', 'X11 CAMO – GRASSLAND'),
  ('x11-camo-hex', 'X11 CAMO – HEX'),
  ('x11-camo-hornet', 'X11 CAMO – HORNET'),
  ('x11-camo-miltech', 'X11 CAMO – MILTECH'),
  ('x11-camo-moss', 'X11 CAMO – MOSS'),
  ('x11-camo-red-urban', 'X11 CAMO – RED URBAN'),
  ('x11-camo-shattered', 'X11 CAMO – SHATTERED'),
  ('x11-camo-wasp', 'X11 CAMO – WASP'),
  ('x11-camo-woodland', 'X11 CAMO – WOODLAND')
on conflict (slug) do update
set name = excluded.name;

